
name: CMake


on: 
   
   push: 
     branches: [ main, imora033/failing_tests ] 
   pull_request: 
     branches: [ main ] 

   workflow_dispatch:


jobs: 
    
  build: 

    runs-on: ubuntu-latest 


    steps: 
        
        - uses: actions/checkout@v2 

        - name: Run a one-line script
          run: |
             cmake .
             make 
             ./test      
