
name: CI

on:
  push:
    branches: [ main, nwarn/ci_setup, nwarn003/passing_tests, imora033/failing_tests ]
  pull_request:
    branches: [ main ]

  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
# This workflow contains a single job called "build"
     build:
         # The type of runner that the job will run on
       runs-on: ubuntu-latest
# Steps represent a sequence of tasks that will be executed as part of the job
       steps: 
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2

# Runs a single command using the runners shell
       - name: Run a one-line script
         run: echo Hello, world!

# Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
            echo Add other actions to build,
            echo test, and deploy your project.

<<<<<<< HEAD
=======
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Runs the tests of rectangle.cpp
      - name: Run gtest
        run: | 
          ./test
<<<<<<< HEAD
>>>>>>> parent of 7c1244a... running main.yml
=======
>>>>>>> parent of 7c1244a... running main.yml
